# https://taskfile.dev

version: "3"

tasks:
  init:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
  up:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  reset:
    cmds:
      - docker compose down -v
  db:
    cmds:
      - docker compose exec mysql bash
